#define NUM_DEVICES					10
#define PAYLOAD_SIZE 				8

#define COMMAND_PAYLOAD_OFFSET		0
#define CHANGE_SPEAKER_SETTING		0
#define DISABLE_SPEAKER				1
#define CHANGE_SPEAKER_VGA			2
#define CHANGE_SPEAKER_FREQUENCY	3
#define CHANGE_SPEAKER_PHASE		4

/*
#define DEV_PAYLOAD_OFFSET			1
#define FREQ_MSB_PAYLOAD_OFFSET		2	
#define FREQ_LSB_PAYLOAD_OFFSET		3
#define PHASE_PAYLOAD_OFFSET		4
#define AMP_MSB_PAYLOAD_OFFSET		5
#define AMP_LSB_PAYLOAD_OFFSET		6

#define DEV_PAYLOAD_OFFSET			1
*/

#define DEV_PAYLOAD_OFFSET			1
#define FREQ_MSB_PAYLOAD_OFFSET		2	
#define FREQ_LSB_PAYLOAD_OFFSET		3
#define PHASE_MSB_PAYLOAD_OFFSET		4
#define PHASE_LSB_PAYLOAD_OFFSET		5
#define AMP_MSB_PAYLOAD_OFFSET		6
#define AMP_LSB_PAYLOAD_OFFSET		7
